name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        racket-variant: ["BC", "CS"]
        racket-version: ["7.0", "7.4", "7.5", "stable", "current"]
        exclude:
          # There were no CS builds of Racket before v7.4.
          - racket-variant: "CS"
            racket-version: "7.0"
        include:
          - package: lathe-ordinals
            install-args: --auto --no-docs --batch
          # There was no `--no-docs` option before v7.5.
          - racket-version: "7.0"
            install-args: --auto --batch
          - racket-version: "7.4"
            install-args: --auto --batch
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Racket '${{ matrix.racket-version }}'
        uses: Bogdanp/setup-racket@v1.1
        with:
          architecture: x64
          distribution: full
          variant: ${{ matrix.racket-variant }}
          version: ${{ matrix.racket-version }}

      # We install each package directory as a linked package, and we
      # automatically fetch all the dependencies. We don't build the
      # docs yet; we'll do that later when we're recompiling the
      # project to check its dependencies.
      - name: Install `${{ matrix.package }}-lib` and its dependencies
        run: raco pkg install ${{ matrix.install-args }} --link "./${{ matrix.package }}-lib/"
      - name: Install `${{ matrix.package }}-doc` and its dependencies
        run: raco pkg install ${{ matrix.install-args }} --link "./${{ matrix.package }}-doc/"
      - name: Install `${{ matrix.package }}-test` and its dependencies
        run: raco pkg install ${{ matrix.install-args }} --link "./${{ matrix.package }}-test/"
      # The main package must be installed after the `...-doc` and
      # `...-test` packages. Otherwise, it'll install stale copies of
      # them from from the Racket package index.
      - name: Install `${{ matrix.package }}` and its dependencies
        run: raco pkg install ${{ matrix.install-args }} --link "./${{ matrix.package }}/"

      # We recompile the collection (the single collection which all
      # these packages populate) and check that the package
      # dependencies declared in each info.rkt are correct.
      - name: Recompile to check dependencies, and build documentation
        run: raco setup --check-pkg-deps --unused-pkg-deps "${{ matrix.package }}"

      # We run tests according to the way the DrDr continuous testing
      # system does. This imitates the settings used by the Racket
      # package index at <https://pkgs.racket-lang.org/>.
      - name: Test `${{ matrix.package }}-lib`
        run: raco test --drdr --package "${{ matrix.package }}-lib"
      - name: Test `${{ matrix.package }}-doc`
        run: raco test --drdr --package "${{ matrix.package }}-doc"
      - name: Test `${{ matrix.package }}-test`
        run: raco test --drdr --package "${{ matrix.package }}-test"
      - name: Test `${{ matrix.package }}`
        run: raco test --drdr --package "${{ matrix.package }}"
